apiVersion: apps/v1
kind: Deployment
metadata:
      name: mysql-deployment
spec:
      selector:
           matchLabels:
                 app: mysql
      replicas: 1           
      template:
           metadata:
                 labels:
                    app: mysql
           spec:
               containers:
                 - name: mysql
                   image: registry.redhat.io/rhel8/mysql-80
                   env:
                    - name: MYSQL_ROOT_PASSWORD
                      value: redhat
                   ports:
                    - containerPort: 3306
                   volumeMounts:
                        - name: my-volume
                          mountPath: /var/lib/mysql
               volumes:
                   - name: my-volume
                     persistentVolumeClaim:
                             claimName: local-pvc
